### ISSUE TITLE
Compatibility issue with busybox stty

### ISSUE THREAD

**Issue by dhuffer** [Xowap/PHP-Serial#1]
While it is possible to use the busybox applet stty, the check is failing because the busybox version of stty does not support the "--version" parameter.
Removing the parameter from the check inside the function phpSerial fixes this issue.

**Comment by Xowap** [comment]
Awesome dhuffer, thank you for this first issue \o/

I fixed it in PR #2, can you check it out and tell me if it works as expected?

It seems to be good with the regular stty as well.

**Comment by dhuffer** [comment]
It's working perfectly with my busybox installation.
Did'nt check with a stock stty.

Thanks for the quick response :-)

**Comment by Xowap** [comment]
@dhuffer you're welcome, it's now merged in the develop branch and I re-released the package :)
